/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class minicarpet5southAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new minicarpet5southAddonDeed();
			}
		}

		[ Constructable ]
		public minicarpet5southAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 2793 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2793 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2792 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2792 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2792 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2792 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2791 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2791 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2790 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2788 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2795 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2791 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2793 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2789 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2794 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2794 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2794 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2794 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2787 );
			AddComponent( ac, 3, 2, 0 );

		}

		public minicarpet5southAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class minicarpet5southAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new minicarpet5southAddon();
			}
		}

		[Constructable]
		public minicarpet5southAddonDeed()
		{
			Name = "minicarpet5south";
		}

		public minicarpet5southAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}