/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class minicarpet1southAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new minicarpet1southAddonDeed();
			}
		}

		[ Constructable ]
		public minicarpet1southAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2807 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2806 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2806 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2757 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2755 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2751 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2806 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2808 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2809 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2756 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2754 );
			AddComponent( ac, 3, 2, 0 );

		}

		public minicarpet1southAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class minicarpet1southAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new minicarpet1southAddon();
			}
		}

		[Constructable]
		public minicarpet1southAddonDeed()
		{
			Name = "minicarpet1south";
		}

		public minicarpet1southAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}