/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class minicarpet4southAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new minicarpet4southAddonDeed();
			}
		}

		[ Constructable ]
		public minicarpet4southAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 2786 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2786 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2785 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2785 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2784 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2782 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2781 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2780 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2779 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2778 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2783 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2785 );
			AddComponent( ac, 3, -1, 0 );

		}

		public minicarpet4southAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class minicarpet4southAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new minicarpet4southAddon();
			}
		}

		[Constructable]
		public minicarpet4southAddonDeed()
		{
			Name = "minicarpet4south";
		}

		public minicarpet4southAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}