/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class minicarpet3eastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new minicarpet3eastAddonDeed();
			}
		}

		[ Constructable ]
		public minicarpet3eastAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 2776 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2776 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2775 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2775 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2775 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2774 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2774 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2773 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2771 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2777 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 2777 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 2777 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 2776 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2776 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2774 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2774 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2772 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 2770 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2769 );
			AddComponent( ac, 1, 2, 0 );

		}

		public minicarpet3eastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class minicarpet3eastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new minicarpet3eastAddon();
			}
		}

		[Constructable]
		public minicarpet3eastAddonDeed()
		{
			Name = "minicarpet3east";
		}

		public minicarpet3eastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}